services:
  front: 
    image: next3enraya
    container_name: front-end
    ports: [3000:3000]
    build: ./front-end
    command: npm start
  back:
    image: next3enraya-b
    container_name: back-end
    build: ./back-end
    ports: [4000:4000]
    command: npm start
